# Generated by Django 3.2.7 on 2021-11-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='CameraBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'CameraBrand',
                'verbose_name_plural': 'CameraBrands',
                'db_table': 'camera_brand',
            },
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'CameraType',
                'verbose_name_plural': 'CameraType',
                'db_table': 'camera_type',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='PhotographerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'PhotographerType',
                'verbose_name_plural': 'PhotographerTypes',
                'db_table': 'photographer_type',
            },
        ),
        migrations.CreateModel(
            name='PhotographyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography_type', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'PhotographyType',
                'verbose_name_plural': 'PhotographyTypes',
                'db_table': 'photography_type',
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'PoliceStation',
                'verbose_name_plural': 'PoliceStations',
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_imgae', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'ProfilePhoto',
                'verbose_name_plural': 'ProfilePhotos',
                'db_table': 'profile_photo',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='ShowcasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph1', models.ImageField(upload_to='images/')),
                ('ph2', models.ImageField(upload_to='images/')),
                ('ph3', models.ImageField(upload_to='images/')),
                ('ph4', models.ImageField(upload_to='images/')),
                ('ph5', models.ImageField(upload_to='images/')),
                ('ph6', models.ImageField(upload_to='images/')),
                ('ph7', models.ImageField(upload_to='images/')),
                ('ph8', models.ImageField(upload_to='images/')),
                ('ph9', models.ImageField(upload_to='images/')),
                ('ph10', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShowcasePhoto',
                'verbose_name_plural': 'ShowcasePhotos',
                'db_table': 'showcase_photo',
            },
        ),
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=17)),
                ('nid_side_1', models.ImageField(upload_to='images/')),
                ('nid_side_2', models.ImageField(upload_to='images/')),
                ('passport_number', models.CharField(max_length=18)),
                ('birth_certificate', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('t_shirt_size', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=18)),
                ('profile_photo', models.ImageField(upload_to='images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.camera')),
                ('photographer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.photographertype')),
                ('photography_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.photographytype')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.showcasephoto')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhotographerProfile',
                'verbose_name_plural': 'PhotographerProfiles',
                'db_table': 'photographer_profile',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=17)),
                ('nid_side_1', models.ImageField(upload_to='images/')),
                ('nid_side_2', models.ImageField(upload_to='images/')),
                ('passport_number', models.CharField(max_length=18)),
                ('birth_certificate', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('t_shirt_size', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ClientProfile',
                'verbose_name_plural': 'ClientProfiles',
                'db_table': 'client_profile',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.camerabrand'),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.cameratype'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.division')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.policestation')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
    ]
