# Generated by Django 3.2.7 on 2021-09-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potosioBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographerprofile',
            options={'verbose_name': 'PhotographerProfile', 'verbose_name_plural': 'PhotographerProfiles'},
        ),
    ]
