# Generated by Django 3.2.7 on 2021-12-11 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('potosioBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Union',
                'verbose_name_plural': 'Unions',
                'db_table': 'union',
            },
        ),
        migrations.RenameModel(
            old_name='PoliceStation',
            new_name='Upazila',
        ),
        migrations.AlterModelOptions(
            name='upazila',
            options={'verbose_name': 'Upazila', 'verbose_name_plural': 'Upazilas'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='police_station',
            new_name='upazila',
        ),
        migrations.RenameField(
            model_name='upazila',
            old_name='police_station',
            new_name='upazila',
        ),
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='division',
            table='division',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
        migrations.AlterModelTable(
            name='upazila',
            table='upazila',
        ),
        migrations.AddField(
            model_name='address',
            name='union',
            field=models.ForeignKey(default=datetime.datetime(2021, 12, 11, 9, 3, 15, 608171, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='potosioBackend.union'),
            preserve_default=False,
        ),
    ]
